# -*- coding: utf-8 -*-
"""Exception Handling Assignment

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zAjdOvWhCrKvh1hGUWOCE54WwoWdd1CD
"""

#Q1
try:  
  a = 10/0  
  print (a)
except ArithmeticError:  
  print ("This statement is raising an arithmetic exception.")
else:  
  print ("Success.")

#Q2
x=int(input("numerator:"))
y=int(input("denominator:"))

try:
  result=x/y
  print(result)
    
except ZeroDivisionError:
  print("Error!!,cannot divide by zero")

#Q3
import math
try:
  print(math.exp(50000))
except OverflowError:
  print("Overflow")

#Q4
import sys 
from termcolor import colored,cprint
print(colored('White font with green background',"white","on_green",attrs=['bold']))
cprint("Green font with yellow background",'green','on_yellow')

#Q5
class MyException(Exception):
  def __init__(self):
    super(Exception,self).__init__
    self.args=("Raised MyException!",)


raise MyException()

